from datetime import date, time
from sqlmodel import Session, select

from app.models.trip_template import TripTemplate
from app.models.route import Route
from app.models.vehicle import Vehicle
from app.models.profile import DriverProfile


def seed_trip_templates(session: Session) -> None:
    """Create TripTemplate rows from the hardcoded schedule. Trips for today
    are then generated by generate_trips_for_date(session, date.today()) in lifespan.
    """
    trip_seed = [
        {"route_name": "Route-1", "direction": "FROM_IUT", "start_time": time(7, 30), "vehicle_number": "NR-208"},
        {"route_name": "Route-1", "direction": "TO_IUT", "start_time": time(8, 5), "vehicle_number": "NR-219"},
        {"route_name": "Route-2", "direction": "FROM_IUT", "start_time": time(8, 15), "vehicle_number": "NR-331"},
        {"route_name": "Route-2", "direction": "TO_IUT", "start_time": time(4, 45), "vehicle_number": "NR-514"},
    ]

    route_map = {r.route_name: r for r in session.exec(select(Route)).all()}
    vehicle_map = {v.vehicle_number: v for v in session.exec(select(Vehicle)).all()}
    profiles = session.exec(select(DriverProfile)).all()
    profile_by_vehicle_id = {p.assigned_vehicle_id: p for p in profiles if p.assigned_vehicle_id}

    for item in trip_seed:
        route = route_map.get(item["route_name"])
        vehicle = vehicle_map.get(item["vehicle_number"])
        if not route or not vehicle:
            continue
        driver_profile = profile_by_vehicle_id.get(vehicle.id)
        if not driver_profile:
            continue

        existing = session.exec(
            select(TripTemplate).where(
                TripTemplate.route_id == route.id,
                TripTemplate.vehicle_id == vehicle.id,
                TripTemplate.direction == item["direction"],
                TripTemplate.start_time == item["start_time"],
            )
        ).first()
        if existing:
            continue

        session.add(
            TripTemplate(
                route_id=route.id,
                vehicle_id=vehicle.id,
                driver_profile_id=driver_profile.id,
                direction=item["direction"],
                start_time=item["start_time"],
                is_active=True,
                valid_from=None,
                valid_to=None,
            )
        )

    session.commit()
